default_stages: [pre-commit]
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: ruff-format
        entry: uv run ruff format
        language: system
        types_or: [python]
        pass_filenames: true

      - id: ruff-lint
        name: ruff-lint
        entry: uv run ruff check
        language: system
        types_or: [python]
        args: ["--fix"]
        pass_filenames: true

      - id: pyright
        name: pyright
        entry: uv run pyright
        language: system
        types_or: [python]
        pass_filenames: true
